## Application properties for Geladeira Mágica
# Server configuration
server.port=8080

# Database configuration
spring.application.name=geladeiraMagica
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:geladeira}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}


## Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=${H2_CONSOLE_ENABLED:false}

# Redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

# Flyway configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# API configuration
API_URL=https://api.openai.com/v1/chat/completions
API_KEY=${OPENAI_API_KEY:}

# CORS configuration
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*

# Static resources configuration
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**

# SWAGGER
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
logging.level.org.springdoc=DEBUG
